# -*- coding: utf-8 -*-
"""butterfly_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PNt7prV5tf4nghKWmv1jtombjOaohslu
"""

#from google.colab import drive
#drive.mount('/content/drive')

#!mkdir -p /content/butterfly_dataset

#!cp -r "/content/drive/MyDrive/Datasets/Image Dataset/data" /content/butterfly_dataset/

from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator
import seaborn as sns
import os
import sklearn
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf
import PIL
from PIL import Image
from tensorflow.keras import layers, models
from tensorflow.keras.applications import EfficientNetB0
from sklearn.model_selection import train_test_split
import joblib

print("Pandas Version:", pd.__version__)
print("Scikit-Learn Version", sklearn.__version__)
print("Tensorflow Version", tf.__version__)
print("PIL Version:", PIL.__version__)
print("Seaborn Version", sns.__version__)
print("Joblib Version:", joblib.__version__)

# Colab local disk path
DATA_DIR = Path("/content/butterfly_dataset/data")

# Checking if the dataset already exists on the local disk
if not os.path.exists(DATA_DIR):
    print("Dataset not found on local disk! Copying folder from Google Drive, please wait 1-2 minutes...")
    !mkdir -p /content/butterfly_dataset
    !cp -r "/content/drive/MyDrive/Datasets/Image Dataset/data" /content/butterfly_dataset/
    print("Copy complete! Data is now ready on Colab's super-fast local disk.")
else:
    print("Data already exists on local disk! No need to copy again.")

#Current Working Path
try:
    BASE_DIR = Path(__file__).resolve().parent.parent
except NameError:
    BASE_DIR = Path.cwd()

#dataset root
DATA_DIR = Path("/content/butterfly_dataset/data")

print("Train folder exists:", os.path.exists(DATA_DIR / "train"))
print("Test folder exists:", os.path.exists(DATA_DIR / "test"))
print("Train csv exists:", os.path.exists(DATA_DIR / "Training_set.csv"))
print("Train csv exists:", os.path.exists(DATA_DIR / "Testing_set.csv"))

#load the training & testing csv dataset
train_df = pd.read_csv(DATA_DIR / "Training_set.csv")
test_df = pd.read_csv(DATA_DIR / "Testing_set.csv")

#image path columns
train_df['image_path'] = train_df['filename'].apply(
    lambda x: os.path.join(DATA_DIR, "train", x)
)

test_df['image_path'] = test_df['filename'].apply(
    lambda x:os.path.join(DATA_DIR, "test", x)
)

train_df.sample(5)

test_df.sample(5)

print("Train Shape:", train_df.shape)
print("Test shape:", test_df.shape)

"""# EDA & validation"""

#checking NAN values
print(f"NAN Values:\n{train_df.isna().sum()}")
print("-------------")
#checking duplicates
print("Duplicate Values:",train_df.duplicated().sum())
print("Total Species:", train_df['label'].value_counts().shape[0])

os.makedirs("/content/drive/MyDrive/Datasets/butterfly_classification_project", exist_ok=True)

plt.figure(figsize=(20, 10))
sns.set_style('whitegrid')
sns.countplot(x=train_df['label'], palette='Set1')
plt.title("Class Distribution", fontsize=16, color="#000000", weight='bold')
plt.xlabel("Species", fontsize=16)
plt.ylabel("Count", fontsize=16)
plt.xticks(rotation=90, color="#000000", weight='bold')
plt.gca().yaxis.set_major_locator(MultipleLocator(5))
plt.yticks(color="#000000", weight='bold')
plt.savefig("/content/drive/MyDrive/Datasets/butterfly_classification_project/class_distribution.png", dpi=300, bbox_inches='tight')
plt.tight_layout()
plt.show()

# Print the minimum and maximum class frequencies for label column
print(f"Minimum frequency: {train_df['label'].value_counts().min()}")
print(f"Maximum frequency: {train_df['label'].value_counts().max()}")

"""Sufficient images in each class; Ok for training"""

# Check for any missing images by verifying if the paths exist
missing_files = train_df[~train_df['image_path'].apply(os.path.exists)]
print("Missing Count:",len(missing_files))

"""# Now Real EDA start"""

#File formate check
valid_ext = (".jpg", ".jpeg", ".png")
invalid_files = []

for path in train_df['image_path']:
    if not path.lower().endswith(valid_ext):
        invalid_files.append(path)

print("Invalid formate images:", len(invalid_files))

#RGB/ corruted image check
#corrupted = []
#non_rgb = []

#for path in train_df['image_path']:
#    try:
#        img = Image.open(path)
#
        #check RGB
#        if img.mode != "RGB":
#            non_rgb.append(path)
#
#            img.verify()
#    except:
#        corrupted.append(path)

#print("Corrupted Images:", len(corrupted))
#print("Non RGB:", len(non_rgb))

#small size image checking
small_files = []
for path in train_df['image_path']:
    try:
        size_kb = os.path.getsize(path) / 1024
        if size_kb < 5:
            small_files.append(path)
    except:
        pass

print("Small Files (<5kb):", len(small_files))

#checking diplicate images
train_files = set(train_df['filename'])

print("Total train images:", len(train_files))
print("unique images:", len(set(train_files)))

"""# Preprocessing"""

lr = LabelEncoder()
train_df['encoded'] = lr.fit_transform(train_df['label'])

joblib.dump(lr, "/content/drive/MyDrive/Datasets/butterfly_classification_project/label_encoder.joblib")
print("Classes:", lr.classes_[:5])

#Train/Validation split
train_df, val_df = train_test_split(
    train_df, test_size=0.2, random_state=42, stratify=train_df['encoded']
)
print("Train size", len(train_df))
print("Val size:", len(val_df))



"""# Augmentation Layer"""

augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.3),
    layers.RandomZoom(0.2),
    layers.RandomBrightness(factor=0.2),
    layers.RandomContrast(factor=0.2),
    layers.RandomTranslation(0.1, 0.1),
    layers.Rescaling(1./255)
], name='augmentation')



def load_image_224(image_path, label):
    img = tf.io.read_file(image_path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, (224, 224))
    return img, label

def load_and_augment_224(image_path, label):
    img, label = load_image_224(image_path, label)
    img = augmentation(img, training=True)
    return img, label

train_ds_cnn = (
    tf.data.Dataset.from_tensor_slices(
        (train_df['image_path'].values, train_df['encoded'].values)
    )
    .map(load_and_augment_224, num_parallel_calls=tf.data.AUTOTUNE)
    .shuffle(1000)
    .batch(32)
    .prefetch(tf.data.AUTOTUNE)
)

val_ds_cnn = (
    tf.data.Dataset.from_tensor_slices(
        (val_df['image_path'].values, val_df['encoded'].values)
    )
    .map(lambda img_path, label: (layers.Rescaling(1./255)(load_image_224(img_path, label)[0]), label), num_parallel_calls=tf.data.AUTOTUNE) # Normalize validation data
    .batch(32)
    .prefetch(tf.data.AUTOTUNE)
)


test_ds = (
    tf.data.Dataset.from_tensor_slices(
        (test_df['image_path'].values)
    )
    .map(lambda p: layers.Rescaling(1./255)(load_image_224(p, 0)[0]))
    .batch(32)
    .prefetch(tf.data.AUTOTUNE)
)
print("TensorFlow datasets re-created with corrected pipeline.")

plt.figure(figsize=(10, 10))
for images, labels in train_ds_cnn.take(1):
    for i in range(9):
        ax = plt.subplot(3, 3, i + 1)
        plt.imshow(images[i].numpy())
        plt.title(lr.inverse_transform([labels[i].numpy()])[0])
        plt.axis("off")
plt.show()

total_classes = len(lr.classes_)

base_cnn_sequential = models.Sequential([
    layers.Input(shape=(224, 224, 3), name='input_layer'),

    #Block1
    layers.Conv2D(32, (3, 3), padding='same', use_bias=False, name='conv1_1'),
    layers.BatchNormalization(name='bn1_1'),
    layers.Activation('relu', name='relu1_1'),
    layers.Conv2D(32, (3, 3), padding='same', use_bias=False, name='conv1_2'),
    layers.BatchNormalization(name='bn1_2'),
    layers.Activation('relu', name='relu1_2'),
    layers.MaxPooling2D(2, 2, name='pool1'),
    layers.Dropout(0.1, name='drop1'),

    #Block2
    layers.Conv2D(64, (3, 3), padding='same', use_bias=False, name='conv2_1'),
    layers.BatchNormalization(name='bn2_1'),
    layers.Activation('relu', name='relu2_1'),
    layers.Conv2D(64, (3, 3), padding='same', use_bias=False, name='conv2_2'),
    layers.BatchNormalization(name='bn2_2'),
    layers.Activation('relu', name='relu2_2'),
    layers.MaxPooling2D(2, 2, name='pool2'),
    layers.Dropout(0.1, name='drop2'),

    #Block3
    layers.Conv2D(128, (3, 3), padding='same', use_bias=False, name='conv3_1'),
    layers.BatchNormalization(name='bn3_1'),
    layers.Activation('relu', name='relu3_1'),
    layers.Conv2D(128, (3, 3), padding='same', use_bias=False, name='conv3_2'),
    layers.BatchNormalization(name='bn3_2'),
    layers.Activation('relu', name='relu3_2'),
    layers.MaxPooling2D(2, 2, name='pool3'),
    layers.Dropout(0.2, name='drop3'),

    #Block4
    layers.Conv2D(256, (3, 3), padding='same', use_bias=False, name='conv4_1'),
    layers.BatchNormalization(name='bn4_1'),
    layers.Activation('relu', name='relu4_1'),
    layers.Conv2D(256, (3, 3), padding='same', use_bias=False, name='conv4_2'),
    layers.BatchNormalization(name='bn4_2'),
    layers.Activation('relu', name='relu4_2'),
    layers.MaxPooling2D(2, 2, name='pool4'),
    layers.Dropout(0.3, name='drop4'),

    #Block5
    layers.Conv2D(512, (3, 3), padding='same', use_bias=False, name='conv5_1'),
    layers.BatchNormalization(name='bn5_1'),
    layers.Activation('relu', name='relu5_1'),
    layers.Conv2D(512, (3, 3), padding='same', use_bias=False, name='conv5_2'),
    layers.BatchNormalization(name='bn5_2'),
    layers.Activation('relu', name='relu5_2'),
    layers.MaxPooling2D(2, 2, name='pool5'),
    layers.Dropout(0.3, name='drop5'),

    #Global Average layer
    layers.GlobalAveragePooling2D(name='global_average_pooling'),
    layers.Dense(512, use_bias=False, name='dense_feature'),
    layers.BatchNormalization(name='dense_drop'),
    layers.Activation('relu', name='relu_dense'),
    layers.Dropout(0.5, name='drop6'),

    #output layer
    layers.Dense(total_classes, activation='softmax', name='output_layer'),
], name='base_cnn_sequential')

base_cnn_sequential.summary()

base_cnn_sequential.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

print("Model re-compiled with a lower learning rate.")

base_cnn_sequential_callback = [
    tf.keras.callbacks.EarlyStopping(
        monitor='val_accuracy',
        patience=15,
        restore_best_weights=True,
        verbose=1
    ),
    tf.keras.callbacks.ModelCheckpoint(
        '/content/drive/MyDrive/Datasets/butterfly_classification_project/base_cnn_model.keras',
        monitor='val_accuracy',
        save_best_only=True,
        mode='max',
        verbose=1
    ),
    tf.keras.callbacks.ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,
        patience=7,
        min_lr=0.0000001,
        verbose=1
    )
]
print("Training callbacks are defined.")







base_cnn_model = base_cnn_sequential.fit(
    train_ds_cnn,
    validation_data=val_ds_cnn,
    epochs=25,
    callbacks=base_cnn_sequential_callback
)

acc_cnn = base_cnn_model.history['accuracy']
val_acc_cnn = base_cnn_model.history['val_accuracy']
loss_cnn = base_cnn_model.history['loss']
val_loss_cnn = base_cnn_model.history['val_loss']
epochs_range_cnn = range(1, len(acc_cnn) + 1)

plt.figure(figsize=(15, 6))

plt.subplot(1, 2, 1)
plt.plot(epochs_range_cnn, acc_cnn, label='Training accuracy', color='#346678', linewidth=2, marker='o', markersize=4)
plt.plot(epochs_range_cnn, val_acc_cnn, label='Validatio accuracy', color='#387658', linewidth=2, marker='x', markersize=4)
plt.title('Base CNN: Training & Validation Accuracy', fontsize=14, fontweight='bold', pad=10)
plt.xlabel('Epochs', fontsize=12)
plt.ylabel('Accuracy', fontsize=12)
plt.legend(loc='lower right', fontsize=11)
plt.grid(True, linestyle='--', alpha=0.6)

plt.subplot(1, 2, 1)
plt.plot(epochs_range_cnn, loss_cnn, label='Training accuracy', color='#346678', linewidth=2, marker='o', markersize=4)
plt.plot(epochs_range_cnn, val_loss_cnn, label='Training accuracy', color='#398778', linewidth=2, marker='x', markersize=4)
plt.title('Base CNN: Training & loss', fontsize=14, fontweight='bold', pad=10)
plt.xlabel('Epochs', fontsize=12)
plt.ylabel('Loss', fontsize=12)
plt.legend(loc='upper right', fontsize=11)
plt.grid(True, linestyle='--', alpha=0.6)

plt.tight_layout()

save_dir = "/content/drive/MyDrive/Datasets/butterfly_classification_project"
os.makedirs(save_dir, exist_ok=True)
save_path = os.path.join(save_dir, "efficientnet_performance_graphs.png")

plt.savefig(save_path, dpi=300, bbox_inches='tight')
print(f"Saaved:{save_path}")







"""# ***EfficientNetB0 Model pipeline***"""

effNet_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.1),
    layers.RandomBrightness(factor=0.1, value_range=(0, 255)),
], name='augmentation')

def load_image_effnet(image_path, label):
    img = tf.io.read_file(image_path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, [224, 224])
    img = tf.cast(img, tf.float32)
    return img, label


def load_and_augment_effnet(image_path, label):
    img, label = load_image_effnet(image_path, label)
    img = effNet_augmentation(img)
    return img, label

train_ds_effnet = (
    tf.data.Dataset.from_tensor_slices(
        (train_df['image_path'].values, train_df['encoded'].values)
    )
    .map(load_and_augment_effnet, num_parallel_calls=tf.data.AUTOTUNE)
    .shuffle(1000)
    .batch(32)
    .prefetch(tf.data.AUTOTUNE)
)
val_ds_effnet = (
    tf.data.Dataset.from_tensor_slices(
        (val_df['image_path'].values, val_df['encoded'].values)
    )
    .map(load_image_effnet, num_parallel_calls=tf.data.AUTOTUNE)
    .batch(32)
    .prefetch(tf.data.AUTOTUNE)
)

effNet_model = EfficientNetB0(
    weights='imagenet',
    include_top=False,
    input_shape=(224, 224, 3)
)
effNet_model.trainable = False

effnet_sequential_model = models.Sequential([
    layers.Input(shape=(224, 224, 3), name='input_layer'),
    effNet_model,
    layers.GlobalAveragePooling2D(name='global_average_effnet'),
    layers.Dropout(0.4, name='frop_effnet_1'),
    layers.Dense(256, activation='relu', name='dense_effnet'),
    layers.Dropout(0.3, name='drop_effnet_2'),
    layers.Dense(total_classes, activation='softmax', name='effnet_output')
], name='EfficientNetB0_Sequential_Butterfly')

efficientne_callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor='val_accuracy',
        patience=6,
        restore_best_weights=True,
        verbose=1
    ),

    tf.keras.callbacks.ModelCheckpoint(
        '/content/drive/MyDrive/Datasets/butterfly_classification_project/Effnet_model.keras',
        monitor='val_accuracy',
        save_best_only=True,
        mode='max',
        verbose=1
    ),

    tf.keras.callbacks.ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,
        patience=5,
        min_lr=1e-7,
        verbose=1
    )

]

effnet_sequential_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
effnet_sequential_model.summary()

efficient_history = effnet_sequential_model.fit(
    train_ds_effnet,
    validation_data=val_ds_effnet,
    epochs=40,
    callbacks=efficientne_callbacks
)

plt.style.use('seaborn-v0_8-whitegrid')

acc = efficient_history.history['accuracy']
val_acc = efficient_history.history['val_accuracy']
loss = efficient_history.history['loss']
val_loss = efficient_history.history['val_loss']
epochs_range = range(1, len(acc) + 1)


plt.figure(figsize=(15, 6))

plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy', color='#1f77b4', linewidth=2, marker='o', markersize=4)
plt.plot(epochs_range, val_acc, label='Validation Accuracy', color='#ff7f0e', linewidth=2, marker='x', markersize=4)
plt.title('EfficientNetB0: Training & Validation Accuracy', fontsize=14, fontweight='bold', pad=10)
plt.xlabel('Epochs', fontsize=12)
plt.ylabel('Accuracy', fontsize=12)
plt.legend(loc='lower right', fontsize=11)
plt.grid(True, linestyle='--', alpha=0.6)

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss', color='#d62728', linewidth=2, marker='o', markersize=4)
plt.plot(epochs_range, val_loss, label='Validation Loss', color='#2ca02c', linewidth=2, marker='x', markersize=4)
plt.title('EfficientNetB0: Training & Validation Loss', fontsize=14, fontweight='bold', pad=10)
plt.xlabel('Epochs', fontsize=12)
plt.ylabel('Loss', fontsize=12)
plt.legend(loc='upper right', fontsize=11)
plt.grid(True, linestyle='--', alpha=0.6)

plt.tight_layout()

save_dir = "/content/drive/MyDrive/Datasets/butterfly_classification_project"
os.makedirs(save_dir, exist_ok=True)
save_path = os.path.join(save_dir, "efficientnet_performance_graphs.png")

plt.savefig(save_path, dpi=300, bbox_inches='tight')
print(f"Saaved:{save_path}")


plt.show()

